name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        run: |
          sudo apt-get install -y lftp
          lftp -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" sftp://${{ secrets.FTP_SERVER }} <<EOF
          set sftp:auto-confirm yes
          mirror -R --delete --exclude .git/ --exclude .github/ --verbose . /www/
          quit
          EOF
